// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oruvcumtglxfnqlhwxpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ydXZjdW10Z2x4Zm5xbGh3eHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTUwNjMsImV4cCI6MjA3MzM3MTA2M30.r6Tx245llx3IKdKYmdSIRcDA7RLFr-gGQj2dXP5yWog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});